// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"context"
)

type Querier interface {
	GetAllProducts(ctx context.Context) ([]Product, error)
	GetProductById(ctx context.Context, id int64) (Product, error)
}

var _ Querier = (*Queries)(nil)
